### ISSUE TITLE
Auto initialize

### ISSUE THREAD

**Issue by TrySound** [jakiestfu/Ripple.js#5]
Do you know [cycle2](https://github.com/malsup/cycle2) plugin?

For initialize it need just to add a className for element.
So, why not do this with Ripple?

**Comment by jakiestfu** [comment]
I prefer not to use auto-initializers mostly because it can be annoying for the user to opt-out of it if they do not want it. Instead, if you want a sort of auto-initialize feature, it should be easy enough to do

``` javascript
$('.btn-ripple').ripple();
```

**Comment by TrySound** [comment]
This initializers will work just with a certain classNames.
.ripple-init
If you don't want to use it, you may not attach this class on page.
Just a feature. I like to use it with bootstrap.

**Comment by TrySound** [comment]
And options could be in data-ripple-\* attributes
