### ISSUE TITLE
VanillaJS

### ISSUE THREAD

**Issue by TrySound** [jakiestfu/Ripple.js#8]
What do you think about using ripple without jQuery or any other dependencies?
I have some experience in this. So, maybe you'll create new branch for this?

**Comment by jakiestfu** [comment]
@TrySound I have plenty of experience in VanillaJS as you can see by my other repos;)

The reasons why chose jQuery to be a dependency of this project are for the following reasons:
1. extension logic
2. dataset polyfill
3. className manipulation
4. offset polyfill
5. event listener polyfill

While these are all easily solved, I felt that it would introduce unnecessary complexity into the project. If this were more popular, or was a recurring issue, I would definitely consider removing jQuery and increasing browser support, but as it stands, it doesn't seem to be something that others have had an issue with.

**Comment by TrySound** [comment]
But:
transform and animation works just in new browsers which do not require polyfills.
Attributes instead of dataset works fine
Again data attributes and className instead of other class manipulation

And I think jQuery take too much place. There is no opportunity to use something like native async loading. That's why I create new vanillajs components.

**Comment by TrySound** [comment]
And you don't use jQuery extension logic. Just jQuery namespace. And clutter it.

**Comment by jakiestfu** [comment]
transform and animation weren't a concern, and interfacing with data-attributes is not the same as working with datasets, which I'd prefer to use. What do you mean by _native async loading_?

I do use jQuery logic quite a bit throughout the script.

**Comment by TrySound** [comment]
You use one-word options, and no need to make camelCase. It's simple to use by filtering all attrniutes.

[async like this](http://www.w3schools.com/tags/att_script_async.asp)

css transformations and animations are base of this plugin. Why need to implement for unsupported browsers? We can check support both of this and prevent init for old browsers.

**Comment by TrySound** [comment]
Let's just try in new branch.
